mysql:
  userName: "root"
  password: "123456abc"
  path: "localhost"
  port: "3306"
  dbName: "ggg_test"
  config: "charset=utf8&parseTime=true"
jwt:
  secret: "my-secret"
  expiresTime: 86400 # 86400 1天
  bufferTime: 604800 # 过期后，刷新时间7天
  issuer: "Misaka"
